#!/usr/bin/env bash
# Regenerate deploy/docker-compose.services.yml from config/services.yml.
# Do not edit the generated file by hand.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/deploy/docker-compose.services.yml"

{
  echo "# GENERATED by scripts/gen-compose.sh from config/services.yml. Do not edit."
  echo "services:"
  awk '
    /^  - name:/ { name=$3 }
    /^    domain:/ { domain=$2 }
    /^    port:/ {
      port=$2
      printf "  %s:\n", name
      printf "    build:\n      context: ..\n      dockerfile: deploy/Dockerfile.service\n      args:\n        SERVICE: %s\n", name
      printf "    image: camel-platform/%s:local\n", name
      printf "    labels:\n      camel.platform.service: \"%s\"\n      camel.platform.domain: \"%s\"\n", name, domain
      printf "    environment:\n      SERVER_PORT: \"8080\"\n      PLATFORM_ENV: local\n      PLATFORM_CONSOLE_URL: http://console:8090\n"
      printf "    ports:\n      - \"%s:8080\"\n", port
      printf "    depends_on:\n      - console\n"
      printf "    restart: unless-stopped\n"
    }
  ' "$ROOT/config/services.yml"
} > "$OUT"
# An empty registry still needs a valid file.
if ! grep -q '^  [a-z]' "$OUT"; then echo "services: {}" > "$OUT"; fi
echo "Wrote deploy/docker-compose.services.yml"
