#!/usr/bin/env bash
# Regenerate deploy/docker-compose.services.yml from config/services.yml.
# Do not edit the generated file by hand.
#
# Per-service environment (credentials, partner endpoints) is read from optional, git-ignored files:
#   deploy/env/<service>.env                  your local overrides
#   services/<service>/dev/.keys/dev.env      written by a service's own dev tooling, if it has any
# Services marked `local-only: true` in the registry get the label camel.platform.local-only=true.
# Services marked `database: true` get SPRING_DATASOURCE_* for their own database (created by the
# db-provision service in deploy/docker-compose.yml) and start after it.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/deploy/docker-compose.services.yml"

{
  echo "# GENERATED by scripts/gen-compose.sh from config/services.yml. Do not edit."
  echo "services:"
  awk '
    function emit() {
      if (name == "") return
      printf "  %s:\n", name
      printf "    build:\n      context: ..\n      dockerfile: deploy/Dockerfile.service\n      args:\n        SERVICE: %s\n", name
      printf "    image: camel-platform/%s:local\n", name
      printf "    labels:\n      camel.platform.service: \"%s\"\n      camel.platform.domain: \"%s\"\n", name, domain
      if (localonly == "true") printf "      camel.platform.local-only: \"true\"\n"
      printf "    environment:\n      SERVER_PORT: \"8080\"\n      PLATFORM_ENV: local\n      PLATFORM_CONSOLE_URL: http://console:8090\n"
      if (database == "true") {
        db = name; gsub("-", "_", db)
        printf "      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/%s\n", db
        printf "      SPRING_DATASOURCE_USERNAME: %s\n", db
        printf "      SPRING_DATASOURCE_PASSWORD: ${SERVICE_DB_PASSWORD:-local-dev-only}\n"
      }
      printf "    env_file:\n"
      printf "      - path: env/%s.env\n        required: false\n", name
      printf "      - path: ../services/%s/dev/.keys/dev.env\n        required: false\n", name
      printf "    ports:\n      - \"%s:8080\"\n", port
      printf "    depends_on:\n      console:\n        condition: service_started\n"
      if (database == "true") printf "      db-provision:\n        condition: service_completed_successfully\n"
      printf "    restart: unless-stopped\n"
    }
    /^  - name:/ { emit(); name=$3; domain="unassigned"; port=""; localonly="false"; database="false" }
    /^    domain:/ { domain=$2 }
    /^    port:/ { port=$2 }
    /^    local-only:/ { localonly=$2 }
    /^    database:/ { database=$2 }
    END { emit() }
  ' "$ROOT/config/services.yml"
} > "$OUT"
# An empty registry still needs a valid file.
if ! grep -q '^  [a-z]' "$OUT"; then echo "services: {}" > "$OUT"; fi
echo "Wrote deploy/docker-compose.services.yml"
